# Generated by Django 2.0.1 on 2018-01-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askstories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askstories',
            name='category_fk',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
