# Generated by Django 2.0.2 on 2018-02-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='showstories',
            name='category_fk',
            field=models.ForeignKey(default='', on_delete='CASCADE', to='showstories.Category'),
        ),
    ]
