# Generated by Django 2.0.2 on 2018-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0002_auto_20180210_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showstories',
            name='category_fk',
            field=models.ForeignKey(default=0, on_delete='CASCADE', to='showstories.Category'),
        ),
    ]
