# Generated by Django 2.0.2 on 2018-02-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0004_auto_20180210_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showstories',
            name='category_fk',
            field=models.ForeignKey(on_delete='CASCADE', to='showstories.Category'),
        ),
    ]
