# Generated by Django 2.0.2 on 2018-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0006_auto_20180210_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AlterField(
            model_name='showstories',
            name='category_fk',
            field=models.ForeignKey(on_delete='CASCADE', to='showstories.Category'),
        ),
    ]
