# Generated by Django 2.0.2 on 2018-02-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0007_auto_20180210_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showstories',
            name='category_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showstories.Category'),
        ),
    ]
