# Generated by Django 2.0.2 on 2018-02-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0008_auto_20180210_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
