# Generated by Django 2.0.2 on 2018-02-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0009_auto_20180210_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.AlterField(
            model_name='showstories',
            name='category_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showstories.Categories'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
