# Generated by Django 2.0.2 on 2018-02-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0010_auto_20180210_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Cat',
        ),
    ]
