# Generated by Django 2.0.2 on 2018-02-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0012_auto_20180210_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showstories',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
