# Generated by Django 2.0.2 on 2018-02-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0013_auto_20180210_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Categories',
        ),
    ]
