# Generated by Django 2.0.2 on 2018-02-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0014_auto_20180210_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Cat',
        ),
    ]
