# Generated by Django 2.0.2 on 2018-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0015_auto_20180210_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showstories',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
